name: Cypress Tests

on:
  push:
    branches:
      -main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Install Dependencies
        run: npm install


      - name: Cypress run
        run: npm run login

        - name: Cypress run
  run: cypress run --spec cypress/e2e/Moduł2/login.cy.js